/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movierentallab.windows;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import movierentallab.classes.Cart;

/**
 *
 * @author mvini
 */
public class Guest extends javax.swing.JFrame implements ActionListener {
    private JFrame window;
    
    Cart cart = new Cart();
    


    /**
     * Creates new form Guest
     */
    public Guest(JFrame window) {
        this.window = window;
        this.setTitle("Guest Account");
        this.setLocationRelativeTo(null);   
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        eMailTxtField = new javax.swing.JTextField();
        cCardTxtField = new javax.swing.JTextField();
        ExpDateTxtField = new javax.swing.JTextField();
        ccvTextField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        payButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Please fill all fields");

        eMailTxtField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        String email = eMailTxtField.getText();
        eMailTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eMailTxtFieldMousePressed(evt);
            }
        });

        cCardTxtField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cCardTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cCardTxtFieldMousePressed(evt);
            }
        });

        ExpDateTxtField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ExpDateTxtField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExpDateTxtFieldMousePressed(evt);
            }
        });
        ExpDateTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpDateTxtFieldActionPerformed(evt);
            }
        });

        ccvTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ccvTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ccvTextFieldMousePressed(evt);
            }
        });
        ccvTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccvTextFieldActionPerformed(evt);
            }
        });

        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        payButton.setText("Pay");
        payButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("E-mail");

        jLabel3.setText("Credit Card Number");

        jLabel4.setText("Expiry Date");

        jLabel5.setText("CVV");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(backButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addComponent(jLabel2)
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eMailTxtField)
                            .addComponent(cCardTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(ExpDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(ccvTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(payButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(370, 370, 370))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eMailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCardTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpDateTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ccvTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(payButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void ExpDateTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpDateTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpDateTxtFieldActionPerformed

    
    // Action Perfomed below: validate the user inputs and create pop ups for the possible errors
    private void payButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payButtonActionPerformed
       try{
       
       String email = eMailTxtField.getText().trim();
       String cCard = cCardTxtField.getText().trim();
       String expDate = ExpDateTxtField.getText().trim();
       String ccv = ccvTextField.getText().trim();
       boolean c1  = false;
       boolean c2  = false;
       boolean c3  = false;
       boolean c4 = false;
       
       
           if(email.isEmpty()){
            JOptionPane.showMessageDialog(this, "Your Email field is empty, Please insert your email");     
           }else{
             c1 = true;  
           }
          
           if(cCard.length() != 16){
               JOptionPane.showMessageDialog(this, "Your Credit Card number is wrong, Please insert 16 digits");               
           }else{
               c2 = true;
           }
           
           if(expDate.length() != 5){
               JOptionPane.showMessageDialog(this, "Your Expiry Date is wrong, Please insert 5 digits");               
           } else{
              c3 = true;  
           }
           if(ccv.length() != 3){
               JOptionPane.showMessageDialog(this, "Your CVV is wrong, Please insert 3 digits");               
           } else{
               c4 = true; 
               
           }  
           
           
           
           if(c1 == true && c2 == true && c3 == true && c4 == true){
               
               int iccv = Integer.parseInt(ccv);
               if(cart.EnterAsGuest(cCard, email, iccv, expDate)){
           int input = JOptionPane.showOptionDialog(null, "Payment Successful! \n\n Please wait for your DVD to be issued. \n\n  Thank You for using Xtra-Vision", "Confirmation", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
     
            if(input == JOptionPane.OK_OPTION){
                this.dispose();}                 }
               else{
               JOptionPane.showMessageDialog(this, "Your Credit Card has an Open Receipt, please return your current DVDs before you rent again");     
               }
               
                              
            
           
      
       }
        
      
       
       }
       catch(Exception e){
       JOptionPane.showMessageDialog(this, "Something is wrong, error: " + e.getMessage());
       }
        
        
        
 
    }//GEN-LAST:event_payButtonActionPerformed
    // Mouse Pressed below: set the text blank when the user click in the text field
    private void eMailTxtFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eMailTxtFieldMousePressed
      eMailTxtField.setText("");

     
    }//GEN-LAST:event_eMailTxtFieldMousePressed
    // Mouse Pressed below: set the text blank when the user click in the text field
    private void cCardTxtFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cCardTxtFieldMousePressed
        // TODO add your handling code here:
        cCardTxtField.setText("");
    }//GEN-LAST:event_cCardTxtFieldMousePressed
    // Mouse Pressed below: set the text blank when the user click in the text field
    private void ExpDateTxtFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpDateTxtFieldMousePressed
        // TODO add your handling code here:
        ExpDateTxtField.setText("");
    }//GEN-LAST:event_ExpDateTxtFieldMousePressed
    // Mouse Pressed below: set the text blank when the user click in the text field
    private void ccvTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ccvTextFieldMousePressed
        // TODO add your handling code here:
        ccvTextField.setText("");
    }//GEN-LAST:event_ccvTextFieldMousePressed
    // Action Performed below: the button goes back to the last frame
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
        Account sMovie = new Account(window);
      
        sMovie.setVisible(true);
        sMovie.setLocationRelativeTo(null);
        sMovie.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_backButtonActionPerformed

    private void ccvTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccvTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ccvTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Guest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ExpDateTxtField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField cCardTxtField;
    private javax.swing.JTextField ccvTextField;
    private javax.swing.JTextField eMailTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton payButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
