/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movierentallab.windows;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import movierentallab.classes.Cart;
import movierentallab.classes.Connector;
import movierentallab.classes.Movie;

/**
 *
 * @author mvini
 */
public class MovieInfo extends javax.swing.JFrame {

    private JFrame window;
    private String movieImage;
    private String mName;
    private String mInfo;
    private int days = 1;
    
    public Cart cart = new Cart();
    

    /**
     * Creates new form MovieInfo
     */
    public MovieInfo(JFrame window, Movie movie) {
        this.mName = movie.getName();
        this.movieImage = movie.getmImage();
        this.window = window;
        this.setTitle(mName);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        Connector conn = new Connector();
        try {
            mInfo = conn.getMovieInfo(mName);
        } catch (SQLException ex) {
            Logger.getLogger(MovieInfo.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Retrieve movie info from DB and store in the object
        initComponents();
    }

    MovieInfo() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mInfoPanel = new javax.swing.JPanel();
        buyButton = new javax.swing.JButton();
        rentButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea(mInfo);
        jLabel1 = new javax.swing.JLabel();
        mImage = new javax.swing.JButton();
        daySelector = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        mInfoPanel.setBackground(new java.awt.Color(204, 204, 204));
        mInfoPanel.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        mInfoPanel.setPreferredSize(new java.awt.Dimension(860, 550));

        buyButton.setText("I WANT TO BUY IT");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        rentButton.setText("RENT FOR: ");
        rentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentButtonActionPerformed(evt);
            }
        });

        goBackButton.setText("BACK To Movie List");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(3);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(3);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setMargin(new java.awt.Insets(4, 7, 2, 7));
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(mName);

        mImage.setIcon(new javax.swing.ImageIcon(getClass().getResource(movieImage)));
        mImage.setBorderPainted(false);
        mImage.setContentAreaFilled(false);
        mImage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mImage.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        mImage.setDefaultCapable(false);
        mImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mImageActionPerformed(evt);
            }
        });

        daySelector.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"1 day", "2 days", "3 days - members", "4 days - members"}));
        daySelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daySelectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mInfoPanelLayout = new javax.swing.GroupLayout(mInfoPanel);
        mInfoPanel.setLayout(mInfoPanelLayout);
        mInfoPanelLayout.setHorizontalGroup(
            mInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mInfoPanelLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mInfoPanelLayout.createSequentialGroup()
                .addGroup(mInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mInfoPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mImage, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(mInfoPanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(buyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(rentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(daySelector, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(goBackButton)))
                .addGap(84, 84, 84))
        );
        mInfoPanelLayout.setVerticalGroup(
            mInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(mInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mInfoPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(mImage, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mInfoPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(mInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rentButton)
                    .addComponent(goBackButton)
                    .addComponent(daySelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentButtonActionPerformed

        try {
            cart.MovieAddIntoCart("RENTED", mName, days);
            
        } catch (SQLException ex) {
            Logger.getLogger(MovieInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
//        System.out.println("I would rent for " + days);  --- TESTING THE BUTTON
        
        this.dispose();
        
        WindowCart sMovie = new WindowCart(window);
        sMovie.setVisible(true);
        sMovie.setLocationRelativeTo(null);
        sMovie.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_rentButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed

        this.dispose();
        SelectMovie mList = new SelectMovie(window);
        mList.setVisible(true);
        mList.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        mList.setLocationRelativeTo(null);
        
        //BACK BUTTON//

    }//GEN-LAST:event_goBackButtonActionPerformed

    private void mImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mImageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mImageActionPerformed

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        
        try {
            cart.MovieAddIntoCart("SOLD", mName);
        } catch (SQLException ex) {
            Logger.getLogger(MovieInfo.class.getName()).log(Level.SEVERE, null, ex);}
        
        this.dispose();
        WindowCart sMovie = new WindowCart(window);

        sMovie.setVisible(true);
        sMovie.setLocationRelativeTo(null);
        sMovie.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }//GEN-LAST:event_buyButtonActionPerformed

    private void daySelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daySelectorActionPerformed
        
        String day = daySelector.getSelectedItem().toString();
                
        if(day.equals("1 day")){
            this.days = 1;} 
        else if(day.equals("2 days")){
            this.days = 2;}
        else if(day.equals("3 days - members")){
            this.days = 3;}
        else if (day.equals("4 days - members")){
            this.days = 4;}
        
        System.out.println("Vaiable days is " + days);
    }//GEN-LAST:event_daySelectorActionPerformed

    public boolean  daySelectorGuest(){
        boolean dayGuest = false;
        
      String day = daySelector.getSelectedItem().toString();
       if(day.equals("3 days - members") || day.equals("4 days - members")){
         dayGuest = true;  
       } else{
           dayGuest = false;
       }
        
     return  dayGuest;  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovieInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovieInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovieInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovieInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButton;
    private javax.swing.JComboBox daySelector;
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton mImage;
    private javax.swing.JPanel mInfoPanel;
    private javax.swing.JButton rentButton;
    // End of variables declaration//GEN-END:variables
}
