/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movierentallab.windows;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import movierentallab.classes.Cart;

/**
 *
 * @author mvini
 */
public class Register extends javax.swing.JFrame implements ActionListener {
    private JFrame window;
    
    Cart cart = new Cart();

    /**
     * Creates new form Register
     */
    public Register(JFrame window) {
        this.window = window;
        this.setTitle("Register Account");
        this.setLocationRelativeTo(null);   
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        infoLabel = new javax.swing.JLabel();
        nameTxtBox = new javax.swing.JTextField();
        eMailTxtBox = new javax.swing.JTextField();
        passwordTxtBox = new javax.swing.JTextField();
        cCardTxtBox = new javax.swing.JTextField();
        cPasswTxtBox = new javax.swing.JTextField();
        ExpDateTxtBox = new javax.swing.JTextField();
        cvvTxtBox = new javax.swing.JTextField();
        goBackButton = new javax.swing.JButton();
        regNpayButton = new javax.swing.JButton();
        fullNameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        passLabel = new javax.swing.JLabel();
        confirmPassLabel = new javax.swing.JLabel();
        cCardNumberLabel = new javax.swing.JLabel();
        expDateLabel = new javax.swing.JLabel();
        ccvLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        infoLabel.setText("Please fill all fields");

        nameTxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameTxtBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nameTxtBoxMousePressed(evt);
            }
        });

        eMailTxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        eMailTxtBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eMailTxtBoxMousePressed(evt);
            }
        });

        passwordTxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordTxtBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                passwordTxtBoxMousePressed(evt);
            }
        });
        passwordTxtBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtBoxActionPerformed(evt);
            }
        });

        cCardTxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cCardTxtBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cCardTxtBoxMousePressed(evt);
            }
        });

        cPasswTxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cPasswTxtBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cPasswTxtBoxMousePressed(evt);
            }
        });

        ExpDateTxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ExpDateTxtBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ExpDateTxtBoxMousePressed(evt);
            }
        });

        cvvTxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cvvTxtBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cvvTxtBoxMousePressed(evt);
            }
        });

        goBackButton.setText("BACK");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        regNpayButton.setText("Register and Pay");
        regNpayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regNpayButtonActionPerformed(evt);
            }
        });

        fullNameLabel.setText("Full Name");

        emailLabel.setText("E-mail");

        passLabel.setText("Password");

        confirmPassLabel.setText("Confirm Password");

        cCardNumberLabel.setText("Credit Card Number");

        expDateLabel.setText("Expiry Date");

        ccvLabel.setText("CVV");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(goBackButton)
                        .addGap(284, 284, 284)
                        .addComponent(regNpayButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(165, 165, 165)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(emailLabel)
                                            .addComponent(fullNameLabel)
                                            .addComponent(passLabel))
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(cCardNumberLabel)
                                            .addComponent(confirmPassLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(expDateLabel)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cCardTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTxtBox)
                            .addComponent(eMailTxtBox)
                            .addComponent(passwordTxtBox)
                            .addComponent(cPasswTxtBox, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ExpDateTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(ccvLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cvvTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(infoLabel)
                .addGap(312, 312, 312))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(infoLabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fullNameLabel))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eMailTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passLabel))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cPasswTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmPassLabel))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cCardTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cCardNumberLabel))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExpDateTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvvTxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expDateLabel)
                    .addComponent(ccvLabel))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(goBackButton)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(regNpayButton)
                        .addContainerGap(56, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void regNpayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regNpayButtonActionPerformed
        
          String fullName = nameTxtBox.getText().trim();
          String email = eMailTxtBox.getText().trim();
          String pass = passwordTxtBox.getText().trim();
          String pass2 = cPasswTxtBox.getText().trim();
          String cCard = cCardTxtBox.getText().trim();
          String expDate = ExpDateTxtBox.getText().trim();
          String ccv = cvvTxtBox.getText().trim(); 
          
          boolean c1  = false;
          boolean c2  = false;
          boolean c3  = false;
          boolean c4 = false;
          boolean c5  = false;
          boolean c6 = false;
          
          
          if(fullName.isEmpty()){
          JOptionPane.showMessageDialog(this, "Your Full Name field is empty, Please insert your name");    
          }else{
            c1 = true;    
          }
          
          if(email.isEmpty()){
          JOptionPane.showMessageDialog(this, "Your Email field is empty, Please insert your email");     
          }else{
            c2 = true;    
          }
          
          if(pass.isEmpty() || pass2.isEmpty()){
            JOptionPane.showMessageDialog(this, "The field Password is empty, Please insert your password");       
            }
          
          if(pass.equals(pass2)){
          c3 = true;
          }else{
          JOptionPane.showMessageDialog(this, "Please make sure your passwords match, insert again");
          }
          
          if(cCard.length() != 16){
          JOptionPane.showMessageDialog(this, "Your Credit Card number is wrong, Please insert 16 digits");               
           }else{
            c4 = true;    
          }
          
          if(expDate.length() != 5){
           JOptionPane.showMessageDialog(this, "Your Expiry Date is wrong, Please insert 5 digits");               
          }else{
            c5 = true;    
          }
          
          if(ccv.length() != 3){
           
           JOptionPane.showMessageDialog(this, "Your CVV is wrong, Please insert 3 NUMBERS");               
           }else{
            c6 = true;    
          }
          
           if(c1 == true && c2 == true && c3 == true && c4 == true && c5 == true && c6 == true){
               
               int iccv = Integer.parseInt(ccv);
               
              try {
                  if(cart.NewUser(cCard, email, fullName, pass, iccv , expDate)){
                      int input = JOptionPane.showOptionDialog(null, "Payment Successful! \n\n Please wait for your DVD to be issued. \n\n  Thank You for using Xtra-Vision", "Confirmation", JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
                      if(input == JOptionPane.OK_OPTION){
                          this.dispose();    }                    }
                  else{
                      JOptionPane.showMessageDialog(this, "Account already registered for this Credit Card, please try a new one or login.");}
              } catch (SQLException ex) {
                  Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
              }
           }            
            
            
              
    
    }//GEN-LAST:event_regNpayButtonActionPerformed
// validates all textFields, then verifies if the information is already in the database, If true: message informing user already registered; If False: Register them into the Database and a confirmation pop up.
    private void nameTxtBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nameTxtBoxMousePressed
    nameTxtBox.setText("");
    }//GEN-LAST:event_nameTxtBoxMousePressed

    private void eMailTxtBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eMailTxtBoxMousePressed
        // TODO add your handling code here:
        eMailTxtBox.setText("");
    }//GEN-LAST:event_eMailTxtBoxMousePressed

    private void passwordTxtBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTxtBoxMousePressed
        // TODO add your handling code here:
        passwordTxtBox.setText("");
    }//GEN-LAST:event_passwordTxtBoxMousePressed

    private void cPasswTxtBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cPasswTxtBoxMousePressed
        // TODO add your handling code here:
        cPasswTxtBox.setText("");
    }//GEN-LAST:event_cPasswTxtBoxMousePressed

    private void cCardTxtBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cCardTxtBoxMousePressed
        // TODO add your handling code here:
        cCardTxtBox.setText("");
    }//GEN-LAST:event_cCardTxtBoxMousePressed

    private void ExpDateTxtBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExpDateTxtBoxMousePressed
        // TODO add your handling code here:
        ExpDateTxtBox.setText("");
    }//GEN-LAST:event_ExpDateTxtBoxMousePressed

    private void cvvTxtBoxMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cvvTxtBoxMousePressed
        // TODO add your handling code here:
        cvvTxtBox.setText("");
    }//GEN-LAST:event_cvvTxtBoxMousePressed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        this.dispose();
        Account sMovie = new Account(window);
      
        sMovie.setVisible(true);
        sMovie.setLocationRelativeTo(null);
        sMovie.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_goBackButtonActionPerformed
//dispose the actual frame and opens a new frame using the same object window to open the SelectMovie frame Class.
    private void passwordTxtBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtBoxActionPerformed
        // TODO add your handling code here:
        passwordTxtBox.setText("");
    }//GEN-LAST:event_passwordTxtBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ExpDateTxtBox;
    private javax.swing.JLabel cCardNumberLabel;
    private javax.swing.JTextField cCardTxtBox;
    private javax.swing.JTextField cPasswTxtBox;
    private javax.swing.JLabel ccvLabel;
    private javax.swing.JLabel confirmPassLabel;
    private javax.swing.JTextField cvvTxtBox;
    private javax.swing.JTextField eMailTxtBox;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel expDateLabel;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nameTxtBox;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField passwordTxtBox;
    private javax.swing.JButton regNpayButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}//Class Fully commented.
