/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movierentallab.windows;

import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import movierentallab.classes.Connector;

/**
 *
 * @author mvini
 */
public class ReturnMovie extends javax.swing.JFrame {
    private JFrame window;
    Connector conn = new Connector();


    /**
     * Creates new form ReturnMovie
     */
    public ReturnMovie(JFrame window) {
        this.window = window;
        this.setLocationRelativeTo(null);   
        this.setTitle("Return a Movie");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        creditCardField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BacktoMmenu = new javax.swing.JButton();
        nextRmovie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setBounds(new java.awt.Rectangle(200, 200, 860, 550));
        setPreferredSize(new java.awt.Dimension(860, 550));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        creditCardField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        creditCardField.setText("xxxx-xxxx-xxxx-xxxx");
        creditCardField.setToolTipText("Enter you Credit card number to access your rented movies");
        creditCardField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        creditCardField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                creditCardFieldMousePressed(evt);
            }
        });
        creditCardField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditCardFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Inform you credit card number and click Next");

        BacktoMmenu.setText("Back to Menu");
        BacktoMmenu.setToolTipText("Go back to Main Menu");
        BacktoMmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BacktoMmenuActionPerformed(evt);
            }
        });

        nextRmovie.setText("Next");
        nextRmovie.setToolTipText("Fetch my Order!");
        nextRmovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextRmovieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(BacktoMmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextRmovie, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(164, 164, 164))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(creditCardField, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(creditCardField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextRmovie, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BacktoMmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creditCardFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditCardFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditCardFieldActionPerformed

    private void BacktoMmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BacktoMmenuActionPerformed
        
//BACK BUTTON//
        
        this.dispose();
        //disposes the actual window
        
        JFrame window = new JFrame("Xtra-Vision");
        window.setBounds(200, 200, 860, 550);
                //Create a new frame
        MainMenu menu = new MainMenu(window);
        window.add(menu);
        window.setLocationRelativeTo(null);
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.setVisible(true);
        //Alocate the panel menu into this new frame.        
        
        //BACK BUTTON//
    }//GEN-LAST:event_BacktoMmenuActionPerformed

    private void creditCardFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_creditCardFieldMousePressed
creditCardField.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_creditCardFieldMousePressed

    private void nextRmovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextRmovieActionPerformed
  try{

          String cCard = creditCardField.getText().trim();
          String cCardDb = null;
          boolean c1 = false;
          
          if(cCard.isEmpty() || cCard.length() != 16){
          JOptionPane.showMessageDialog(this, "Something wrong, Please insert 16 digits of your Credit Card");    
          }else{
              
                    String query = "SELECT creditcard FROM cart WHERE creditcard =" + cCard +";";
                    Statement selector = conn.getConnection().createStatement();
                    
                    ResultSet rs = selector.executeQuery(query);//Get days amount
                    if(rs.next()){
                    cCardDb = rs.getString(1);
                    System.out.println("movie has " + cCardDb + " Days ");}
                    conn.CloseConnection();                       
                    
                    if(cCard.equals(cCardDb)){
                    JOptionPane.showMessageDialog(this, "We have found your Order");     
                     c1 = true;    
                    }else{
                    JOptionPane.showMessageDialog(this, "I'm sorry, we could't find your order :( ");      
                    }
                    
                    if(c1== true){
                        this.dispose();
                         CheckOut sMovie = new CheckOut(window);
                         sMovie.setVisible(true);
                         sMovie.setLocationRelativeTo(null);
                          sMovie.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);   
        
                        
                        
                    }
 
              
              
              
              
              
              
               
          } 
          
          
          
          
      }catch(Exception e){
        JOptionPane.showMessageDialog(this, "Something is wrong, error: " + e.getMessage());           }
       
        
        
        

    }//GEN-LAST:event_nextRmovieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BacktoMmenu;
    private javax.swing.JTextField creditCardField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextRmovie;
    // End of variables declaration//GEN-END:variables
}
