/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movierentallab.windows;

import javax.swing.JFrame;
import movierentallab.MovieRentalLab;
import movierentallab.classes.Movie;


/**
 *
 * @author mvini
 */
public class SelectMovie extends javax.swing.JFrame {
    private JFrame window;
    
    private Movie movie = new Movie();
    
    
        
    /**
     * Creates new form SelectMovie
     */
    public SelectMovie(JFrame window) {
        this.window = window;
        this.setLocationRelativeTo(null);   
        this.setTitle("Select your Movie");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backToMmenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        moviePanel = new javax.swing.JPanel();
        matrixButton = new javax.swing.JButton();
        shrekButton = new javax.swing.JButton();
        titanicbutton = new javax.swing.JButton();
        avengersButton = new javax.swing.JButton();
        tLionKingButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(860, 550));

        backToMmenu.setText("Back To Main Menu");
        backToMmenu.setToolTipText("Back to Main Menu");
        backToMmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToMmenuActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel2.setText("Top Choices!");

        moviePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        matrixButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movierentallab/Pics/The Matrix.png"))); // NOI18N
        matrixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrixButtonActionPerformed(evt);
            }
        });

        shrekButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movierentallab/Pics/Shrek.png"))); // NOI18N
        shrekButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shrekButtonActionPerformed(evt);
            }
        });

        titanicbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movierentallab/Pics/Titanic.png"))); // NOI18N
        titanicbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titanicbuttonActionPerformed(evt);
            }
        });

        avengersButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movierentallab/Pics/Avengers.png"))); // NOI18N
        avengersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avengersButtonActionPerformed(evt);
            }
        });

        tLionKingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/movierentallab/Pics/The Lion King.png"))); // NOI18N
        tLionKingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tLionKingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout moviePanelLayout = new javax.swing.GroupLayout(moviePanel);
        moviePanel.setLayout(moviePanelLayout);
        moviePanelLayout.setHorizontalGroup(
            moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moviePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titanicbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(matrixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(shrekButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(avengersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tLionKingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        moviePanelLayout.setVerticalGroup(
            moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, moviePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(titanicbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matrixButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(shrekButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(avengersButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(tLionKingButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );

        jScrollPane1.setViewportView(moviePanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(backToMmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(backToMmenu)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backToMmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToMmenuActionPerformed
        
        //BACK BUTTON//
        
        this.dispose();
        //disposes the actual window
        
        JFrame window = new JFrame("Xtra-Vision");
        window.setBounds(200, 200, 860, 550);
                //Create a new frame
        MainMenu menu = new MainMenu(window);
        window.add(menu);
        window.setLocationRelativeTo(null);
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.setVisible(true);
        //Alocate the panel menu into this new frame.        
        
        
        
    }//GEN-LAST:event_backToMmenuActionPerformed

    private void tLionKingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tLionKingButtonActionPerformed
        movie.setName("The Lion King (1994)");
        movie.setmImage("/movierentallab/Pics/The Lion King.png");
                
        MovieInfo mInfo = new MovieInfo(window, movie);
        window.dispose();
        mInfo.setVisible(true);
        mInfo.setBounds(0, 0, 860, 550);
        mInfo.setLocationRelativeTo(null);
        mInfo.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
             
    }//GEN-LAST:event_tLionKingButtonActionPerformed

    private void titanicbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titanicbuttonActionPerformed
        movie.setName("Titanic (1997)");
        movie.setmImage("/movierentallab/Pics/Titanic.png");
                
        MovieInfo mInfo = new MovieInfo(window, movie);
        window.dispose();
        mInfo.setVisible(true);
        mInfo.setBounds(0, 0, 860, 550);
        mInfo.setLocationRelativeTo(null);
        mInfo.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);   
    }//GEN-LAST:event_titanicbuttonActionPerformed

    private void matrixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrixButtonActionPerformed
         movie.setName("The Matrix (1999)");
         movie.setmImage("/movierentallab/Pics/The Matrix.png");
                
        MovieInfo mInfo = new MovieInfo(window, movie);
        window.dispose();
        mInfo.setVisible(true);
        mInfo.setBounds(0, 0, 860, 550);
        mInfo.setLocationRelativeTo(null);
        mInfo.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
    }//GEN-LAST:event_matrixButtonActionPerformed

    private void shrekButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shrekButtonActionPerformed
        movie.setName("Shrek");
        movie.setmImage("/movierentallab/Pics/Shrek.png");
                
        MovieInfo mInfo = new MovieInfo(window, movie);
        window.dispose();
        mInfo.setVisible(true);
        mInfo.setBounds(0, 0, 860, 550);
        mInfo.setLocationRelativeTo(null);
        mInfo.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_shrekButtonActionPerformed

    private void avengersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avengersButtonActionPerformed
        movie.setName("Avengers Assemble");
        movie.setmImage("/movierentallab/Pics/Avengers.png");
                
        MovieInfo mInfo = new MovieInfo(window, movie);
        window.dispose();
        mInfo.setVisible(true);
        mInfo.setBounds(0, 0, 860, 550);
        mInfo.setLocationRelativeTo(null);
        mInfo.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_avengersButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton avengersButton;
    private javax.swing.JButton backToMmenu;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton matrixButton;
    private javax.swing.JPanel moviePanel;
    private javax.swing.JButton shrekButton;
    private javax.swing.JButton tLionKingButton;
    private javax.swing.JButton titanicbutton;
    // End of variables declaration//GEN-END:variables
}
