/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package movierentallab.windows;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import movierentallab.classes.Cart;

/**
 *
 * @author aliss
 */
public class WindowCart extends javax.swing.JFrame {

    private JFrame window;
    
    Cart cart = new Cart();
    
    private String mPanel1;
    private String mPanel2;
    private String mPanel3;
    private String mPanel4;
    
    private String mType1;
    private String mType2;
    private String mType3;
    private String mType4;
    
    private float fPrice1;
    private String Price1;
    private float fPrice2;
    private String Price2;
    private float fPrice3;
    private String Price3;
    private float fPrice4;
    private String Price4;
    
    private int idays1;
    private String days1;
    private int idays2;
    private String days2;
    private int idays3;
    private String days3;
    private int idays4;
    private String days4;
    
    private float ftotal1;
    private String total1;
    private float ftotal2;
    private String total2;
    private float ftotal3;
    private String total3;
    private float ftotal4;
    private String total4;
     
    public WindowCart(JFrame window) {
        
        this.window = window;
        this.setTitle("Xtra-Vision Cart");
        this.setLocationRelativeTo(null);   
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

  
        try {
           
        this.mPanel1 = cart.PanelMovieName(1);        
        this.mType1 = cart.PanelType(1);
        this.fPrice1 = cart.PanelPrice(1);
        this.Price1 = Float.toString(fPrice1);
        this.idays1 = cart.PanelDays(1);
        this.days1 = Integer.toString(idays1);
        ftotal1 = this.idays1 * this.fPrice1;
        total1 = Float.toString(ftotal1);
        //All Labels for Panel 1
        
        this.mPanel2 = cart.PanelMovieName(2); 
        this.mType2 = cart.PanelType(2);
        this.fPrice2 = cart.PanelPrice(2);
        this.Price2 = Float.toString(fPrice2);
        this.idays2 = cart.PanelDays(2);
        this.days2 = Integer.toString(idays2);
        ftotal2 = this.idays2 * this.fPrice2;
        total2 = Float.toString(ftotal2);
        //All Labels for Panel 2
        
        this.mPanel3 = cart.PanelMovieName(3);        
        this.mType3 = cart.PanelType(3);
        this.fPrice3 = cart.PanelPrice(3);
        this.Price3 = Float.toString(fPrice3);
        this.idays3 = cart.PanelDays(3);
        this.days3 = Integer.toString(idays3);
        ftotal3 = this.idays3 * this.fPrice3;
        total3 = Float.toString(ftotal3);
        //All Labels for Panel 3
        
        this.mPanel4 = cart.PanelMovieName(4);        
        this.mType4 = cart.PanelType(4);
        this.fPrice4 = cart.PanelPrice(4);
        this.Price4 = Float.toString(fPrice4);
        this.idays4 = cart.PanelDays(4);
        this.days4 = Integer.toString(idays4);
        ftotal4 = this.idays4 * this.fPrice4;
        total4 = Float.toString(ftotal4);
        //All Labels for Panel 4
        
        } catch (SQLException ex) {
            Logger.getLogger(WindowCart.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageLabel = new javax.swing.JLabel();
        labelDelete = new javax.swing.JLabel();
        labelTitlePanel = new javax.swing.JLabel();
        labelTypePanel = new javax.swing.JLabel();
        labelTitlePrice = new javax.swing.JLabel();
        labelTitleDays = new javax.swing.JLabel();
        labelTitleTotal = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        deletePanel1 = new javax.swing.JButton();
        labelMovie1 = new javax.swing.JLabel();
        labelStatus1 = new javax.swing.JLabel();
        labelPrice1 = new javax.swing.JLabel();
        labelDays1 = new javax.swing.JLabel();
        labelTotal1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        deletePanel2 = new javax.swing.JButton();
        labelMovie2 = new javax.swing.JLabel();
        labelStatus2 = new javax.swing.JLabel();
        labelPrice2 = new javax.swing.JLabel();
        labelDays2 = new javax.swing.JLabel();
        labelTotal2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        deletePanel4 = new javax.swing.JButton();
        labelMovie4 = new javax.swing.JLabel();
        labelStatus4 = new javax.swing.JLabel();
        labelPrice4 = new javax.swing.JLabel();
        labelDays4 = new javax.swing.JLabel();
        labelTotal4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        deletePanel3 = new javax.swing.JButton();
        labelMovie3 = new javax.swing.JLabel();
        labelStatus3 = new javax.swing.JLabel();
        labelPrice3 = new javax.swing.JLabel();
        labelDays3 = new javax.swing.JLabel();
        labelTotal3 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        checkOutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        messageLabel.setText("As a guest you pay the full amount and you can be refunded at your DVD return");

        labelDelete.setText("Delete from Cart");

        labelTitlePanel.setText("Movie");

        labelTypePanel.setText("Buying/Renting");

        labelTitlePrice.setText("Price");

        labelTitleDays.setText("Days");

        labelTitleTotal.setText("Total");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        deletePanel1.setText("Delete");
        deletePanel1.setActionCommand("DELETE");
        deletePanel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePanel1ActionPerformed(evt);
            }
        });

        labelMovie1.setText(mPanel1);

        labelStatus1.setText(mType1);

        labelPrice1.setText(Price1);

        labelDays1.setText(days1);

        labelTotal1.setText(total1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(deletePanel1)
                .addGap(55, 55, 55)
                .addComponent(labelMovie1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(labelStatus1)
                .addGap(107, 107, 107)
                .addComponent(labelPrice1)
                .addGap(84, 84, 84)
                .addComponent(labelDays1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTotal1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletePanel1)
                    .addComponent(labelStatus1)
                    .addComponent(labelPrice1)
                    .addComponent(labelDays1)
                    .addComponent(labelTotal1)
                    .addComponent(labelMovie1))
                .addGap(34, 34, 34))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        deletePanel2.setText("Delete");
        deletePanel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePanel2ActionPerformed(evt);
            }
        });

        labelMovie2.setText(mPanel2);

        labelStatus2.setText(mType2);

        labelPrice2.setText(Price2);

        labelDays2.setText(days2);

        labelTotal2.setText(total2);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(deletePanel2)
                .addGap(57, 57, 57)
                .addComponent(labelMovie2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(labelStatus2)
                .addGap(112, 112, 112)
                .addComponent(labelPrice2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDays2)
                .addGap(75, 75, 75)
                .addComponent(labelTotal2)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletePanel2)
                    .addComponent(labelMovie2)
                    .addComponent(labelStatus2)
                    .addComponent(labelPrice2)
                    .addComponent(labelDays2)
                    .addComponent(labelTotal2))
                .addGap(33, 33, 33))
        );

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        deletePanel4.setText("Delete");
        deletePanel4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePanel4ActionPerformed(evt);
            }
        });

        labelMovie4.setText(mPanel4);

        labelStatus4.setText(mType4);

        labelPrice4.setText(Price4);

        labelDays4.setText(days4);

        labelTotal4.setText(total4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(deletePanel4)
                .addGap(51, 51, 51)
                .addComponent(labelMovie4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(labelStatus4)
                .addGap(121, 121, 121)
                .addComponent(labelPrice4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(labelDays4)
                .addGap(77, 77, 77)
                .addComponent(labelTotal4)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletePanel4)
                    .addComponent(labelMovie4)
                    .addComponent(labelStatus4)
                    .addComponent(labelPrice4)
                    .addComponent(labelDays4)
                    .addComponent(labelTotal4))
                .addGap(33, 33, 33))
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        deletePanel3.setText("Delete");
        deletePanel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePanel3ActionPerformed(evt);
            }
        });

        labelMovie3.setText(mPanel3);

        labelStatus3.setText(mType3);

        labelPrice3.setText(Price3);

        labelDays3.setText(days3);

        labelTotal3.setText(total3);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(deletePanel3)
                .addGap(55, 55, 55)
                .addComponent(labelMovie3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(labelStatus3)
                .addGap(116, 116, 116)
                .addComponent(labelPrice3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelDays3)
                .addGap(76, 76, 76)
                .addComponent(labelTotal3)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletePanel3)
                    .addComponent(labelMovie3)
                    .addComponent(labelStatus3)
                    .addComponent(labelPrice3)
                    .addComponent(labelDays3)
                    .addComponent(labelTotal3))
                .addGap(33, 33, 33))
        );

        backButton.setText("BACK");
        backButton.setToolTipText("");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        checkOutButton.setText("CHECK OUT");
        checkOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(labelDelete)
                .addGap(68, 68, 68)
                .addComponent(labelTitlePanel)
                .addGap(108, 108, 108)
                .addComponent(labelTypePanel)
                .addGap(109, 109, 109)
                .addComponent(labelTitlePrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitleDays)
                .addGap(101, 101, 101)
                .addComponent(labelTitleTotal)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(backButton)
                .addGap(701, 701, 701)
                .addComponent(checkOutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(messageLabel)
                        .addGap(202, 202, 202))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(messageLabel)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDelete)
                    .addComponent(labelTitlePanel)
                    .addComponent(labelTypePanel)
                    .addComponent(labelTitleDays)
                    .addComponent(labelTitleTotal)
                    .addComponent(labelTitlePrice))
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(checkOutButton))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void deletePanel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePanel1ActionPerformed
        try {
            cart.RemoveFromCart(1);
        } catch (SQLException ex) {Logger.getLogger(WindowCart.class.getName()).log(Level.SEVERE, null, ex);}
        
        this.dispose();
        WindowCart wCart = new WindowCart(window);
        wCart.setVisible(true);
        wCart.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        wCart.setLocationRelativeTo(null);        
    }//GEN-LAST:event_deletePanel1ActionPerformed

    private void deletePanel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePanel2ActionPerformed
        try {
            cart.RemoveFromCart(2);
        } catch (SQLException ex) {Logger.getLogger(WindowCart.class.getName()).log(Level.SEVERE, null, ex);}
        
        this.dispose();
        WindowCart wCart = new WindowCart(window);
        wCart.setVisible(true);
        wCart.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        wCart.setLocationRelativeTo(null);
    }//GEN-LAST:event_deletePanel2ActionPerformed

    private void deletePanel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePanel3ActionPerformed
        try {
            cart.RemoveFromCart(3);
        } catch (SQLException ex) {Logger.getLogger(WindowCart.class.getName()).log(Level.SEVERE, null, ex);}
        
        this.dispose();
        WindowCart wCart = new WindowCart(window);
        wCart.setVisible(true);
        wCart.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        wCart.setLocationRelativeTo(null);
    }//GEN-LAST:event_deletePanel3ActionPerformed

    private void deletePanel4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePanel4ActionPerformed
        try {
            cart.RemoveFromCart(4);
        } catch (SQLException ex) {Logger.getLogger(WindowCart.class.getName()).log(Level.SEVERE, null, ex);}
        
        this.dispose();
        WindowCart wCart = new WindowCart(window);
        wCart.setVisible(true);
        wCart.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        wCart.setLocationRelativeTo(null);
    }//GEN-LAST:event_deletePanel4ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        this.dispose();
        SelectMovie sMovie = new SelectMovie(window);

        sMovie.setVisible(true);
        sMovie.setLocationRelativeTo(null);
        sMovie.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_backButtonActionPerformed

    private void checkOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutButtonActionPerformed
        this.dispose();
        Account sMovie = new Account(window);

        sMovie.setVisible(true);
        sMovie.setLocationRelativeTo(null);
        sMovie.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_checkOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WindowCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WindowCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WindowCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WindowCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton checkOutButton;
    private javax.swing.JButton deletePanel1;
    private javax.swing.JButton deletePanel2;
    private javax.swing.JButton deletePanel3;
    private javax.swing.JButton deletePanel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelDays1;
    private javax.swing.JLabel labelDays2;
    private javax.swing.JLabel labelDays3;
    private javax.swing.JLabel labelDays4;
    private javax.swing.JLabel labelDelete;
    private javax.swing.JLabel labelMovie1;
    private javax.swing.JLabel labelMovie2;
    private javax.swing.JLabel labelMovie3;
    private javax.swing.JLabel labelMovie4;
    private javax.swing.JLabel labelPrice1;
    private javax.swing.JLabel labelPrice2;
    private javax.swing.JLabel labelPrice3;
    private javax.swing.JLabel labelPrice4;
    private javax.swing.JLabel labelStatus1;
    private javax.swing.JLabel labelStatus2;
    private javax.swing.JLabel labelStatus3;
    private javax.swing.JLabel labelStatus4;
    private javax.swing.JLabel labelTitleDays;
    private javax.swing.JLabel labelTitlePanel;
    private javax.swing.JLabel labelTitlePrice;
    private javax.swing.JLabel labelTitleTotal;
    private javax.swing.JLabel labelTotal1;
    private javax.swing.JLabel labelTotal2;
    private javax.swing.JLabel labelTotal3;
    private javax.swing.JLabel labelTotal4;
    private javax.swing.JLabel labelTypePanel;
    private javax.swing.JLabel messageLabel;
    // End of variables declaration//GEN-END:variables
}
